### ISSUE TITLE
Can I train the YOLOv3 model for another class of objects?

### ISSUE THREAD

**Issue by monocongo** [toolboc/IntelligentEdgeHOL#1]
I'm interested to find out if it is possible to perform transfer learning on the YOLOv3 model in order to train it to detect classes of objects that are not already available. (I have a dataset of training images/annotations that is in COCO format.) Can you advise as to whether or not this is easily done and if so any guidance on how I might accomplish this?

In any event kudos on your work here, this is impressive.

**Comment by toolboc** [comment]
I haven't done this myself but there is no reason why you could not.  There are a number of articles out there like [this one](https://medium.com/@manivannan_data/how-to-train-yolov3-to-detect-custom-objects-ccbcafeb13d2) which describe the process of training YOLOv3 for detection of custom objects.  You would need to update the model ( .cfg and .weights in the yolo folder of this project) and rebuild a new module image which includes the updated model.
