### ISSUE TITLE
Is it possible to run the docker image without Azure?

### ISSUE THREAD

**Issue by mitchross** [toolboc/IntelligentEdgeHOL#3]
My Azure subscription ran out. Id like to run the docker image without having to deploy via IoT hub? Im new when it comes to docker. I know some very bare bones basics, but im not sure how the docker "folder" works. Is there a way I can just extract the folder and run some command to pull down the images?

**Comment by toolboc** [comment]
Unfortunately, this project is at it's heart an "Azure IoT Edge" module which requires that you have some services enabled in Azure for it to work.  Technically, you only need a [free-tier IoT Hub](https://azure.microsoft.com/en-us/pricing/details/iot-hub/) which allows for a total of 8,000 messages per day.
