### ISSUE TITLE
Access anywhere

### ISSUE THREAD

**Issue by ondeviceai** [toolboc/IntelligentEdgeHOL#4]
Hi @toolboc,

How to access the web server outside local network?

**Comment by toolboc** [comment]
There are a number of ways to do this:

The most basic would involve enabling port forwarding on your router to forward traffic on a specific port to you port 80 of your Nvidia device.  This is a bit of work and would require setting up DNS and configuring the router appropriately.

For an even easier solution, take a look at [PageKite](https://pagekite.net/).  This solution easily allows you to expose a locally running service that is publicly accessible through an external url.
